# Path aliases for Bun runtime
[alias]
"@controllers" = "./src/controllers"
"@models" = "./src/models"
"@config" = "./src/config"
"@middlewares" = "./src/middlewares"
"@routes" = "./src/routes"
"@socket" = "./src/socket"
"@constants" = "./src/constant"
"@utils" = "./src/utils"
"@tests" = "./src/tests"
"@v1" = "./src/routes/v1"
"@validators" = "./src/validators"
"@app" = "./src"