export const SOCKET_EVENTS = {
  ONLINE_USERS: "online_users",
  PRIVATE_MESSAGE: "private_message",
  MESSAGE_SENT: "message_sent",
  USER_OFFLINE: "user_offline",
  ERROR_MESSAGE: "error_message",
  MESSAGE_DELETED: "message_deleted",
  TYPING: "typing",
  MESSAGE_READ: "message_read",
  GROUP_MESSAGE: "group_message",
  JOIN_GROUP: "join_group",
  LEAVE_GROUP: "leave_group",
  READ_RECEIPT: "read_receipt",
  USER_CAME_ONLINE: "user_came_online",
  USER_WENT_OFFLINE: "user_went_offline",

  FRIEND_REQUEST_RECEIVED: "friend_request_received",
  FRIEND_REQUEST_ACCEPTED: "friend_request_accepted",
  FRIEND_REQUEST_REJECTED: "friend_request_rejected",
  FRIEND_REMOVED: "friend_removed",

  GROUP_CREATED: "group_created",
  GROUP_MEMBER_ADDED: "group_member_added",
  GROUP_MEMBER_REMOVED: "group_member_removed",
  GROUP_MEMBER_LEFT: "group_member_left",
  GROUP_DELETED: "group_deleted",
};
